package main;

import archivo.*;
import grafos.*;
import java.io.*;
import java.awt.Color;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import datos.Datos;
import java.awt.Image;
import java.util.List;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marco
 */
public class Interfaz extends javax.swing.JFrame {

    JFileChooser seleccionado = new JFileChooser();
    File archivo;
    GestionArchivos gestion = new GestionArchivos();
    Grafos g = new Grafos();

    /**
     * Creates new form Main
     */
    int xMouse, yMouse;

    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bt_prueba = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        mapa = new javax.swing.JLabel();
        bt_buscar = new javax.swing.JLabel();
        bt_abrir = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_xd = new javax.swing.JTable();
        mapaGrafo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Mapa");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Detalles");

        bt_prueba.setBackground(new java.awt.Color(255, 0, 51));
        bt_prueba.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_prueba.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bt_pruebaMouseDragged(evt);
            }
        });
        bt_prueba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_pruebaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_pruebaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_pruebaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_pruebaMousePressed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscar");

        javax.swing.GroupLayout bt_pruebaLayout = new javax.swing.GroupLayout(bt_prueba);
        bt_prueba.setLayout(bt_pruebaLayout);
        bt_pruebaLayout.setHorizontalGroup(
            bt_pruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_pruebaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        bt_pruebaLayout.setVerticalGroup(
            bt_pruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_pruebaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        mapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-mapa-64.png"))); // NOI18N
        mapa.setText("jLabel5");
        mapa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mapa.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mapaMouseDragged(evt);
            }
        });
        mapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mapaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mapaMousePressed(evt);
            }
        });

        bt_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-ver-archivo-50.png"))); // NOI18N
        bt_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_buscar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bt_buscarMouseDragged(evt);
            }
        });
        bt_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_buscarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_buscarMousePressed(evt);
            }
        });

        bt_abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-abrir-carpeta-50.png"))); // NOI18N
        bt_abrir.setText("jLabel4");
        bt_abrir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_abrir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bt_abrirMouseDragged(evt);
            }
        });
        bt_abrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_abrirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_abrirMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_abrirMousePressed(evt);
            }
        });

        Tabla_xd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Origen ", "Destino", "Tiempo_V", "Tiempo_P", "Gasolina", "Energia", "Distancia"
            }
        ));
        jScrollPane1.setViewportView(Tabla_xd);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(51, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(mapaGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(93, 93, 93))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mapa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(358, 358, 358)
                .addComponent(bt_prueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_abrir)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mapa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(bt_prueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(mapaGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void leerArchivo(String contenido) {
        try {
            // Abre el archivo
            List<Datos> listaDatos = new ArrayList<>();
            // Dividir el  contenido del arhivo en lineas
            String[] lineas = contenido.split("\n");
            // Leer cada linea del archivo
            for (String linea : lineas) {
                //System.out.println("Línea leída: " + linea);
                // Divide la linea en partes utilizando "|" como delimitador
                String[] partes = linea.split("\\|");
                // Extrae los datos de cada parte
                String origen = partes[0];
                String destino = partes[1];
                int tiempoVehiculo = Integer.parseInt(partes[2]);
                int tiempoPie = Integer.parseInt(partes[3]);
                int consumoGas = Integer.parseInt(partes[4]);
                int desgastePersona = Integer.parseInt(partes[5]);
                int distancia = Integer.parseInt(partes[6]);

                // Creamos objetos
                Datos datos = new Datos(origen, destino, tiempoVehiculo, tiempoPie, consumoGas, desgastePersona, distancia);
                listaDatos.add(datos);
            }

            // Mostrar datos en la tabla
            DefaultTableModel model = (DefaultTableModel) Tabla_xd.getModel();
            // Limpiamos la tabla
            model.setRowCount(0);
            // Iteramos sobre la lista de datos 
            for (Datos datos : listaDatos) {
                Object[] fila = {
                    datos.getDestino(), datos.getOrigen(),
                    datos.getTiempo_vehiculo(),
                    datos.getTiempo_pie(),
                    datos.getConsumo_gas(),
                    datos.getDesgaste_persona(),
                    datos.getDistancia()
                };
                model.addRow(fila);
            }
            jScrollPane1.repaint();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void mostrarGrafo() {
        // Carga la imagen del grafo y la establece 
        ImageIcon ig = new ImageIcon("grafo.png");
        mapaGrafo.setIcon(ig);
        // vuelve a pintar 
        mapaGrafo.repaint();
        // mejorar grafo
        SetImagen(mapaGrafo, "grafo.png", this);

    }
    
    // Arreglando imagen 
    public  void SetImagen( JLabel label,String url , JFrame ventana){
        ImageIcon imagen = new ImageIcon(url);
        Icon icon= new ImageIcon(imagen.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH));
        label.setIcon(icon);
        ventana.repaint();
    }
    
    // funcion para limpiar datos 
    private void limpiarDatos(){
        // Limpiar el JLabel 
        mapaGrafo.setIcon(null);
        mapaGrafo.repaint();
        
        // Limpiar la tabla 
        DefaultTableModel model = (DefaultTableModel) Tabla_xd.getModel();
        model.setRowCount(0);
    }
    private void bt_pruebaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pruebaMousePressed
        // TODO add your handling code here
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_bt_pruebaMousePressed

    private void bt_pruebaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pruebaMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_bt_pruebaMouseDragged

    private void bt_pruebaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pruebaMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Este es un mensaje de información", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bt_pruebaMouseClicked

    private void bt_pruebaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pruebaMouseEntered
        // TODO add your handling code here:
        bt_prueba.setBackground(Color.BLUE);
    }//GEN-LAST:event_bt_pruebaMouseEntered

    private void bt_pruebaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pruebaMouseExited
        // TODO add your handling code here:
        bt_prueba.setBackground(Color.RED);
    }//GEN-LAST:event_bt_pruebaMouseExited

    // BOTON BUSCAR
    private void bt_buscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_buscarMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_bt_buscarMousePressed

    private void bt_buscarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_buscarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_bt_buscarMouseDragged

    private void bt_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_buscarMouseClicked
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "valor buscar", "Buscar", JOptionPane.INFORMATION_MESSAGE);
        limpiarDatos();
    }//GEN-LAST:event_bt_buscarMouseClicked

    // BOTON ABRIR
    private void bt_abrirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_abrirMouseEntered

    }//GEN-LAST:event_bt_abrirMouseEntered

    private void bt_abrirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_abrirMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_bt_abrirMousePressed

    private void bt_abrirMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_abrirMouseDragged
        // TODO add your handling code here:
        int x = evt.getX();
        int y = evt.getY();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_bt_abrirMouseDragged

    private void bt_abrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_abrirMouseClicked
        // TODO add your handling code here:
        if (seleccionado.showDialog(null, "Abrir Archivo") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionado.getSelectedFile();
            if (archivo.canRead()) {
                if (archivo.getName().endsWith("txt")) {
                    String contenido = gestion.Abrir(archivo);
                    // Agregamos el lugar donde se manda el archivo
                    leerArchivo(contenido);
                    g.generarGrafo(contenido);
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor ingrese el archivo de entrada");
                }
            }
        }
    }//GEN-LAST:event_bt_abrirMouseClicked

    private void mapaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapaMouseClicked
        // TODO add your handling code here:
        mostrarGrafo();
    }//GEN-LAST:event_mapaMouseClicked

    private void mapaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_mapaMouseEntered

    private void mapaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapaMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_mapaMousePressed

    private void mapaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapaMouseDragged
        // TODO add your handling code here:
        int x = evt.getX();
        int y = evt.getY();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_mapaMouseDragged
    /**
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_xd;
    private javax.swing.JLabel bt_abrir;
    private javax.swing.JLabel bt_buscar;
    private javax.swing.JPanel bt_prueba;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mapa;
    private javax.swing.JLabel mapaGrafo;
    // End of variables declaration//GEN-END:variables
}
